### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#10]
Boas 

Quando ligado por bluetooth , em vez de phones the ouvido 
Não seria melhor colocar , auscultador.

**Comment by KcNirvana** [comment]
Boas...
Podes mandar 1 print dessa situação?
Obrigado

**Comment by Franciscoestima** [comment]
![screenshot_2018-08-08-15-32-51-666_com android incallui](https://user-images.githubusercontent.com/25460498/43844435-a45d771c-9b21-11e8-8c40-acb3979ba1f3.png)

**Comment by Franciscoestima** [comment]
Você colocou auriculares ?

Qdo estamos ligados ao bluetooth do carro e queres mudar para o telefone .
Não seria melhor colocar telefone por exemplo , acho mais intuitivo.
Obrigado
