### ISSUE TITLE
Câmara

### ISSUE THREAD

**Issue by fermateus** [KcNirvana/MIUI-XML-10-PORTUGUESE#11]
Boas,

Podes verificar nas propriedades da câmara, onde está data e hora, será "Marca de água".
Porque tens ja tens a opção "Adicionar data e hora na foto".

Abraço

**Comment by fermateus** [comment]
![img_20180808_210037](https://user-images.githubusercontent.com/6343249/43862029-896edca0-9b50-11e8-9676-55c6c8a57569.jpg)
Vê se consegues ver...
Thanks 🤣

**Comment by KcNirvana** [comment]
Boas rapaz...
Eu não tenho a 2ª função.
Ambas são "Marca d'água".
Podes me dizer se ambas as funções fazem a mesma coisa?
Obrigado

Grande abraço

**Comment by fermateus** [comment]
Olá 
Adicionar data e hora na foto (adiciona data e hora)
2 função Escreve "Adicionar Marca d'água" que vai adicionar na foto o nome do dispositivo.
Abraço :)
![img_20180811_111019](https://user-images.githubusercontent.com/6343249/43990749-22878142-9d60-11e8-96f6-0baf401df074.jpg)
