### ISSUE TITLE
Várias traduções 

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#15]
![img_20180819_000630](https://user-images.githubusercontent.com/25460498/44303889-42e1d480-a344-11e8-9dc8-f067b7e592e5.jpg)
![screenshot_2018-08-18-23-55-06-290_com android settings](https://user-images.githubusercontent.com/25460498/44303890-483f1f00-a344-11e8-9c8c-f4f8bc827fb0.png)
![img_20180818_235255](https://user-images.githubusercontent.com/25460498/44303891-4d9c6980-a344-11e8-8d3c-24b65b760245.jpg)

**Comment by KcNirvana** [comment]
SS3 corrigido

**Comment by KcNirvana** [comment]
@Franciscoestima 
SS1:
"Cloud Print" é uma aplicação Google, logo não é traduzida por este repositório.
Para o "Default Print Service" podes-me indicar qual o dispositivo que estás a utilizar?

Obrigado

**Comment by Franciscoestima** [comment]
Ok compreendo 
Estava a tentar adicionar uma impressora local 
Da HP
