### ISSUE TITLE
Notificações

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#16]
Barra de estado : 
Primeiro quadrado para traduzir .

Área de notificações:
Segundo , penso que a frase está um pouco confusa
![img_20180825_124652](https://user-images.githubusercontent.com/25460498/44618045-b87b0280-a866-11e8-858b-fce356819ef0.jpg)

**Comment by KcNirvana** [comment]
Boas...
O primeiro tá corrigido, só não foi a tempo da rom desta semana.

O segundo significa que pode mostrar a área de notificacoes em ecras d bloqueio seguros ( c palavra-passe).
Aceito sugestões...
😉

**Comment by Franciscoestima** [comment]
Ok , porreiro.Pois o segundo , visto que é essa a função.Até esta enquadrado.Uma pergunta off toppic Os ícones no topo do ecrã do lado esquerdo deixaram de aparecer na miui10 quando o ecrã está bloqueado, é mesmo problema da ROM original?Em 25/08/2018 13:23, KcNirvana <notifications@github.com> escreveu:Boas...
O primeiro tá corrigido, só não foi a tempo da rom desta semana.
O segundo significa que pode mostrar a área de notificacoes em ecras d bloqueio seguros ( c palavra-passe).
Aceito sugestões...
😉

**Comment by KcNirvana** [comment]
Boas...
Yap...
Na MIUI10 deixaram de aparecer os ícones do ecrã de bloqueio...
Nada com que não se possa viver não é?
Muito obrigado pelos erros de tradução.

Grande abraço

**Comment by Franciscoestima** [comment]
sim claro que se vive, era só uma questão de habito...

Eu por exemplo só usava os ícones para notificação com o ecrã  
bloqueado e as notificações pop-up quando o telemóvel estava  
desbloqueado.
E agora tenho que usar as notificações completas no ecrã de  
bloqueio.... são gostos ...lol

Se eu puder ajudar em mais alguma coisa , avisa .

Obrigado.

Citando KcNirvana <notifications@github.com>:

> Boas...
> Yap...
> Na MIUI10 deixaram de aparecer os ícones do ecrã de bloqueio...
> Nada com que não se possa viver não é?
> Muito obrigado pelos erros de tradução.
>
> Grande abraço
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].

 

Ligações:
---------
[1]  
https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/16#issuecomment-416154330
[2]

**Comment by Franciscoestima** [comment]
Boas companheiroSerá que me pode ajudar com este erro ?Na rom global funka na boa Desculpe estar a chatear Está aplicação está a fazer-me muita falta Em 27/08/2018 10:03, franciscoestima@sapo.pt escreveu:

sim claro que se vive, era só uma questão de habito...

Eu por exemplo só usava os ícones para notificação com o ecrã bloqueado e as notificações pop-up quando o telemóvel estava desbloqueado.
E agora tenho que usar as notificações completas no ecrã de bloqueio.... são gostos ...lol

Se eu puder ajudar em mais alguma coisa , avisa .

Obrigado.
Citando KcNirvana <notifications@github.com>:

Boas...
Yap...
Na MIUI10 deixaram de aparecer os ícones do ecrã de bloqueio...
Nada com que não se possa viver não é?
Muito obrigado pelos erros de tradução.
Grande abraço

**Comment by KcNirvana** [comment]
Boas...
Qual erro?

**Comment by Franciscoestima** [comment]
Em 27/08/2018 22:34, KcNirvana <notifications@github.com> escreveu:Boas...
Qual erro?

**Comment by KcNirvana** [comment]
Bom dia...
Continuo sem ver nada....

**Comment by Franciscoestima** [comment]
Bom dia,

Deveria ir como anexo...

Este report é de uma app que funciona na global e deixou de funcionar  
assim que instalei a .EU
 

Citando KcNirvana <notifications@github.com>:

> Bom dia...
> Continuo sem ver nada....
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].

 

Ligações:
---------
[1]  
https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/16#issuecomment-416525226
[2]

**Comment by KcNirvana** [comment]
Pois mas não está a ir...
Entra no Github e mete a imagem lá senão nunca mais saimos daqui....
😃

**Comment by Franciscoestima** [comment]
![screenshot_2018-08-27-22-27-05-377_com miui bugreport](https://user-images.githubusercontent.com/25460498/44717204-5c0d2280-aab4-11e8-8e1a-28affe625773.png)
Estava a usar o outlook e anexava o screenshot . lol

**Comment by KcNirvana** [comment]
Esse erro transcende um bocado/bocadão o meu conhecimento...
Tens o face unlock activo?

**Comment by Franciscoestima** [comment]
sim tenho ( mas já teve desligada )mas não tem nada a ver.
é a própria app que não arranca .

Já tentei em varias Rom´s da EU ( miui 8 , miui 9 e agora 10 ) e  
vários telefones e não funciona.
Se tiverem a rom oficial funciona bem ...

Ja tentei falar com o Ingrizy mas ele nunca me respondeu , parece-me  
que faltam livrarias do android ( framework / outras ) , 
não sou o único a queixar-me ... :(
 

Citando KcNirvana <notifications@github.com>:

> Esse erro transcende um bocado/bocadão o meu conhecimento...
> Tens o face unlock activo?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].

 

Ligações:
---------
[1]  
https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/16#issuecomment-416532346
[2]

**Comment by KcNirvana** [comment]
Para descargo de consciência qual é a app?

**Comment by Franciscoestima** [comment]
X-diag Pro3 

da Launch .
 

Citando KcNirvana <notifications@github.com>:

> Para descargo de consciência qual é a app?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].

 

Ligações:
---------
[1]  
https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/16#issuecomment-416536848
[2]

**Comment by KcNirvana** [comment]
Boas...
Instalei a apk daqui https://launchtechusa.com/x-431-pro3/
Não sei se é a correcta, mas a aplicação abriu. Não passou do ecrã inicial, onde não consegui perceber o que é que faz mas também não sei para que serve

**Comment by Franciscoestima** [comment]
Pode ser essa aplicação , mas tem que passar do ecrã inicial e aparecer os menus. Se esperares vai dar erro. Já experimentei várias .
A rom tem alguns ficheiros em falta .

**Comment by Franciscoestima** [comment]
![screenshot_2018-08-29-13-56-16-236_com google android googlequicksearchbox](https://user-images.githubusercontent.com/25460498/44789074-9a2d4380-ab93-11e8-86c6-ca3137c69aef.png)
Tem que abrir assim
É o software para diagnóstico automóvel

**Comment by KcNirvana** [comment]
Boas...
Tive a comparar as bibliotecas da versão global com a versão xiaomi.eu e estão lá as bibliotecas de que a app se queixa.
Tenta por aqui o erro e diz que na versão global funciona para ver s alguem te ajuda a resolver o problema..
https://xiaomi.eu/community/threads/8-8-23-confirmed-issues-faq.45907/

grande abraço

**Comment by Franciscoestima** [comment]
Muito obrigado pela ajuda amigo Em 29/08/2018 17:09, KcNirvana <notifications@github.com> escreveu:Boas...
Tive a comparar as bibliotecas da versão global com a versão xiaomi.eu e estão lá as bibliotecas de que a app se queixa.
Tenta por aqui o erro e diz que na versão global funciona para ver s alguem te ajuda a resolver o problema..
https://xiaomi.eu/community/threads/8-8-23-confirmed-issues-faq.45907/
grande abraço
