### ISSUE TITLE
Tempo

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#17]
24h 

![screenshot_2018-08-27-08-38-50-422_com miui weather2](https://user-images.githubusercontent.com/25460498/44647271-7d4b1180-a9d5-11e8-89e0-9dd7be23910a.png)

**Comment by KcNirvana** [comment]
Boas...
Tá corrigido, só não foi a tempo da rom desta semana.
Obrigado.

Grande abraço
