### ISSUE TITLE
Ecrã inicial e recentes

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#18]
Tradução:
![screenshot_2018-08-31-23-51-55-090_com miui home](https://user-images.githubusercontent.com/25460498/44938909-6f9cdf80-ad79-11e8-8a69-f6457b8e2a8d.png)

**Comment by KcNirvana** [comment]
Boas...
Já corrigido em https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/commit/ea9f655c1013856f6fe8ca667408e89d9b6e4a29
Disponível na próxima versão.
Abraço
