### ISSUE TITLE
Ecrã em tamanho grande inteiro

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#19]
Tradução:
![screenshot_2018-08-31-23-57-21-674_com android settings](https://user-images.githubusercontent.com/25460498/44938961-cdc9c280-ad79-11e8-90f1-1470e9371a72.png)

**Comment by KcNirvana** [comment]
Boas...
Já corrigido em https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/commit/ea9f655c1013856f6fe8ca667408e89d9b6e4a29
Disponível na próxima versão.
Abraço
