### ISSUE TITLE
Definição em ecrã de bloqueio e impressões digitais em inglês

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MIUI-XML-10-PORTUGUESE#2]
Nas definições Ecrã de bloqueio e impressões digitais>Definições Avançadas>Com o dispositivo Bloqueado, a primeira opção para não aparecer notificações no ecrã com este bloqueado está em inglês.

XiaoMI Mi Mix 2S 8.6.18
![screenshot_2018-06-21-22-23-24-233_com android settings](https://user-images.githubusercontent.com/37287217/41746666-1d69b48a-75a3-11e8-81b8-e0f500f1d75c.png)

**Comment by KcNirvana** [comment]
Boas...
Obrigado pelo report.
Corrigido para a próxima versão.
Abraço
