### ISSUE TITLE
[8.8.3] Falta tradução na opção FIRST AID na app de SEGURANÇA

### ISSUE THREAD

**Issue by Juvetech** [KcNirvana/MIUI-XML-10-PORTUGUESE#20]
Falta tradução na opção FIRST AID na app de SEGURANÇA

![41001156_558742301263452_7670330300915777536_n](https://user-images.githubusercontent.com/8722736/45089868-7b83fb00-b105-11e8-98ff-d0f51e677fe8.png)
![41129082_918580115005997_2587983521171636224_n](https://user-images.githubusercontent.com/8722736/45089869-7c1c9180-b105-11e8-920c-803132f9cabc.png)

**Comment by KcNirvana** [comment]
Boas...
Corrigido no commit 2889022ecc006656021ef7c05ac3825b1f7104dc.
Obrigado.
