### ISSUE TITLE
[8.8.3] Falta tradução na ECRÃ INICIAL E RECENTES

### ISSUE THREAD

**Issue by Juvetech** [KcNirvana/MIUI-XML-10-PORTUGUESE#21]
Caminho:
Definições de ecrã inicial -> Definições -> Mais

![40758243_907654829435520_4397117672886632448_n](https://user-images.githubusercontent.com/8722736/45095570-4c29ba00-b116-11e8-8e47-d2a9b6d5984d.png)

**Comment by KcNirvana** [comment]
Boas...
Corrigido no commit ea9f655c1013856f6fe8ca667408e89d9b6e4a29.
Obrigado.
