### ISSUE TITLE
Contactos - enviar mensagem - WhatsApp

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#25]
![screenshot_2018-09-11-08-27-47-100_com android contacts](https://user-images.githubusercontent.com/25460498/45419128-4a17ac00-b67e-11e8-930b-2a002d1ecaf2.png)

**Comment by KcNirvana** [comment]
Boas...
No meu tá tudo traduzido...
![img_20180912_193511](https://user-images.githubusercontent.com/12718890/45462074-1da37480-b6fe-11e8-9371-0d47fcb57560.jpg)

**Comment by Franciscoestima** [comment]
Bom dia,

Apaguei a app e voltei a instalar e ja esta tudo ok.

Obrigado.
 

Citando KcNirvana <notifications@github.com>:

> Boas...
> No meu tá tudo traduzido...
> [1]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[2], or mute the thread[3].

 

Ligações:
---------
[1]  
https://user-images.githubusercontent.com/12718890/45462074-1da37480-b6fe-11e8-9371-0d47fcb57560.jpg
[2]  
https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/25#issuecomment-420854138
[3]
