### ISSUE TITLE
8.11.8 [Mi Mix 2S] - super night mode

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MIUI-XML-10-PORTUGUESE#29]
A nova função "super night mode" nos mix 2s e variantes do mi8 aparece como "NOCTURNO" e não NOTURNO.

**Comment by NunoRocha89** [comment]
Screenshot
![screenshot_2018-11-09-10-46-44-367_com android camera](https://user-images.githubusercontent.com/37287217/48258840-09ce7300-e40e-11e8-8f1e-2475c7b1e806.png)

**Comment by KcNirvana** [comment]
Bom dia,
O que está correcto.
http://dicionario.priberam.org/nocturno
Obrigado.

**Comment by NunoRocha89** [comment]
Supostamente essa palavra foi alterada com o novo acordo ortográfico daí não ter o C.

**Comment by NunoRocha89** [comment]
![screenshot_2018-11-09-13-00-47-041_pt portoeditora android dicionario lingua_portuguesa](https://user-images.githubusercontent.com/37287217/48263932-ab11f500-e41f-11e8-8185-953898683f56.png)
