### ISSUE TITLE
WiFi > denificoes avançadas com linha em inglês

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MIUI-XML-10-PORTUGUESE#3]
Quando se está na página de WiFi e se vai para as definições avançadas, aparece uma linha em inglês no separador "gerir ligações"

**Comment by NunoRocha89** [comment]
![screenshot_2018-06-22-12-08-04-805_com android settings](https://user-images.githubusercontent.com/37287217/41773786-26c0bdcc-7615-11e8-8c5f-c1e374bf764a.png)

**Comment by NunoRocha89** [comment]
Já agora, não tem nada a ver com isto mas há alguma possibilidade de alterar o LTE para 4G no Rom? 4G penso ser o termo mais indicado para a Europa como tem no Rom global.

**Comment by KcNirvana** [comment]
Boas...
Sim existe a possibilidade de passar de LTE para 4G.
A questão do LTE tem a ver com a região das roms xiaomi.eu que está na região PL e que tem todos os desenvolvimentos para essa mesma região.
Se mudares de região para PT, passa-te a aparecer o 4G mas perdes funcionalidades como o Face Unlock.

Isto não é nada que se possa fazer com a tradução.
Não sei se é possível alterar a região directamente na ROM.
Se não for, só através do build.prop

Abraço

**Comment by NunoRocha89** [comment]
Sim no build.prop da pois já vi isso lá mas era mais por curiosidade. Nada de importante.
Obrigado

**Comment by NunoRocha89** [comment]
Na versão 8.6.21 a linha contínua a aparecer em inglês.
![screenshot_2018-06-23-10-49-25-949_com android settings](https://user-images.githubusercontent.com/37287217/41808329-a41421ce-76d3-11e8-92c6-b920aa3ae403.png)

**Comment by KcNirvana** [comment]
Boas...
Como eu não sei se a tradução chegou a ser atualizada para a versão 8.6.21, vou manter este issue como fechado por enquanto.
Se esta semana continuar, reabro.
Abraço
