### ISSUE TITLE
Notificações e Barra de estado [9.3.28]

### ISSUE THREAD

**Issue by Juvetech** [KcNirvana/MIUI-XML-10-PORTUGUESE#31]
Menu de Notificações e Barra de estado têm bastante conteúdo em inglês.

Equipamento: Mi6
Definições -> Definições de Sistema -> Notificações e Barra de estado

**Comment by KcNirvana** [comment]
Boas...
Podes postar um SS, dispositivo e versão?
Obrigado.

Abraço

**Comment by Juvetech** [comment]
![55875445_1234523673379891_2014097975424319488_n](https://user-images.githubusercontent.com/8722736/55434819-5e76b400-5590-11e9-9cb8-aa53dcb39b99.png)
![56218256_866506923694012_3577020661584887808_n](https://user-images.githubusercontent.com/8722736/55434820-5e76b400-5590-11e9-96db-681ba6510e2d.png)
![56427003_323041831896528_6646922993953931264_n](https://user-images.githubusercontent.com/8722736/55434821-5e76b400-5590-11e9-9265-f16177f2beb8.png)

**Comment by KcNirvana** [comment]
Boas,
As correções foram feitas após a rom ser compilada.
https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/commit/5d510e61f8a5ff05cd5ed9f4328ea2844501f697

Vou manter este issue aberto até à próxima versão para validar se já está corrigido.
Obrigado
