### ISSUE TITLE
Calendar FC

### ISSUE THREAD

**Issue by ingbrzy** [KcNirvana/MIUI-XML-10-PORTUGUESE#32]
https://xiaomi.eu/community/threads/9-4-18.50189/page-15#post-483474

**Comment by KcNirvana** [comment]
@ingbrzy 
I don't have that issue on my Vince.
Do you know what the string that causes the bug?
Thanks

**Comment by ingbrzy** [comment]
you can check for outdated variables by jBart translation parser...

**Comment by ingbrzy** [comment]
https://github.com/ingbrzy/Xiaomi.eu-MIUIv10-XML-Compare/blob/a2423e7531d23b2a9367b5276e2505b0a4592d15/wayne/Calendar.apk/res/values/strings.xml#L541
