### ISSUE TITLE
[MI9] [9.5.30] caracteres chineses em aviso na camera

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MIUI-XML-10-PORTUGUESE#33]
Tenho um MI9 com a versão 9.5.30 e quando vou a APP da câmara, se tapar totalmente a camera, aparece no ecrã um aviso em chinês.
![Screenshot_2019-06-03-14-21-53-063_com android camera](https://user-images.githubusercontent.com/37287217/58805263-a7d49580-860b-11e9-892d-39f6cfad05cf.png)

**Comment by KcNirvana** [comment]
Boas...
Para já não existe forma de traduzir isso, mas vamos aguardar por novas versões.
Abraço

**Comment by NunoRocha89** [comment]
Boas, ragora que na ultima ROM que flashei (9.6.5) agora a info aparece em inglês (CURRENT ORIENTETION).
