### ISSUE TITLE
Opções de "Indicador de Bateria" em Inglês

### ISSUE THREAD

**Issue by ghost** [KcNirvana/MIUI-XML-10-PORTUGUESE#37]
Caminho: Definições -> Notificações e barra de estado -> Indicador de bateria

![Screenshot_2019-06-15-14-26-25-456_com android settings](https://user-images.githubusercontent.com/51855775/59552039-eb1ef480-8f79-11e9-9e16-e56a8189d4c4.png)

**Comment by KcNirvana** [comment]
Boas,
Parece que ta a utilizar uma versão global da Miui.
Pode por um ss da versao da rom?
Obrigado

**Comment by ghost** [comment]
Está aqui o SS.

![Screenshot_2019-06-15-15-30-23-530_com android settings](https://user-images.githubusercontent.com/51855775/59552764-bf543c80-8f82-11e9-8249-3700c5a65f11.png)

**Comment by KcNirvana** [comment]
Obrigado.
Esse erro já foi corrigido para a próxima stable release.
Abraço
