### ISSUE TITLE
[9.7.4] [MI9] Algumas coisas em inglês e caracteres estranhos 

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MIUI-XML-10-PORTUGUESE#39]
No menu "Password and security" além do título não estar traduzido como mencionado noutro ticket dado a Xiaomi ter reorganizado os layout das definições, na secção de localização, aparece ligado mas depois aparecem caracteres estranhos. Não sei se por ventura tinha de aparecer se era alta precisão, ou outro tipo de ligação.
Tem mais alguns textos em inglês.
![Screenshot_2019-07-05-09-49-04-549_com android settings](https://user-images.githubusercontent.com/37287217/60710394-887ea000-9f0a-11e9-9ac7-335a8a889514.jpg)

**Comment by KcNirvana** [comment]
Boas...
Tudo corrigido.
Vou aproveitar para tirar uma dúvida pk não sei se isto acontece só no meu.
Antigamente quando punha em Não incomodar, basicamente as notificações das aplicações apareciam mas não tinham nem som nem vibração.
Com esta ROM, essas notificações começaram a ter vibração.
Ou seja, ter em modo Não incomodar ou Silêncio vai dar ao mesmo.
Também é assim no teu?
Grande abraço

**Comment by NunoRocha89** [comment]
Vou confirmar e já dou feedback.

**Comment by NunoRocha89** [comment]
No meu fez pior... Liguei o modo DND e pedi a um colega para me ligar e isto vibrou e tocou... Eu uso o telemóvel sempre em silêncio porque uso um amazfit e prefiro receber as notificações apenas. O DND nao está a funcionar de todo para mim.

**Comment by KcNirvana** [comment]
Deve ser um bug na ROM da China...
Espero que corrijam antes de acabarem com as Beta
Muito obrigado.
👍
