### ISSUE TITLE
Widget em ingles

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MIUI-XML-10-PORTUGUESE#4]
É normal o widget das horas ter a data e a meteorologia em inglês?
Ainda estive a rpocurar das linhas da aplicação do calendário mas está tudo traduzido.
Como usando se carrega no widget ele abre logo o calendário, pensei que tivesse associado.
![screenshot_2018-06-22-13-41-13-030_com miui home](https://user-images.githubusercontent.com/37287217/41777144-4cd73db2-7622-11e8-9e0f-51364ff84061.png)

**Comment by NunoRocha89** [comment]
Na nova versão 8.6.21 a data já aparece em pt-PT mas a condição meteorologica nao.

Mi mix 2s

**Comment by NunoRocha89** [comment]
![screenshot_2018-06-23-10-49-38-523_com miui home](https://user-images.githubusercontent.com/37287217/41808311-5bd352d6-76d3-11e8-99cc-5ed41d2111d5.png)

**Comment by NunoRocha89** [comment]
Eu acho que aquele "clear" nao da para traduzir pois a minha namorada tem um redmi note 5 e tive a testar e este mesmo widget lá aparece igual mas ela tem a versão global stable instalada. Noutro widget das horas já aparece bem.

**Comment by NunoRocha89** [comment]
É estranho mas se tiver os dois widgets na mesma alguns, ambos ficam em português,
![screenshot_2018-06-23-12-31-05-510_com miui home](https://user-images.githubusercontent.com/37287217/41809205-767e12b6-76e1-11e8-9fca-31dd61f82fb2.png)

**Comment by NunoRocha89** [comment]
É estranho mas se ambos os widgets estiverem na mesma página, ambos ficam em português.
![screenshot_2018-06-23-12-33-13-381_com miui home](https://user-images.githubusercontent.com/37287217/41809212-9ccaf6aa-76e1-11e8-8b19-ff69d18094eb.png)

**Comment by KcNirvana** [comment]
Boas...
Por acaso dá.
É apenas uma questão de procurar...
Mas como ainda não há Miui10 para o Redmi 5 Plus, ainda não fiz grandes testes em Miui10.


![screenshot_2018-06-25-09-13-07-910_com miui home](https://user-images.githubusercontent.com/12718890/41838441-5a2009ee-7858-11e8-8a04-6d2d248b3406.png)

**Comment by NunoRocha89** [comment]
No da minha namorada só meti a xiaomi.eu ontem mas no meu mi mix 2s já uso a muito e continua em inglês a parte da meteorologia. Mas se usar outro widget já dá em pt.
Deve ser algum bug.

**Comment by KcNirvana** [comment]
Não é possível a alteração para PT.
Obrigado.

Abraço
