### ISSUE TITLE
[9.6.7] actualização e nocturno

### ISSUE THREAD

**Issue by NunoRocha89** [KcNirvana/MIUI-XML-10-PORTUGUESE#41]
Boas mais uma vez, já te tinha contactado pelo menos por causa do noturno e na altura mandaste um link onde falava em nocturno. No rom global sempre teve noturno mas agora lá no tal site do dicionário também já fala em noturno por causa do acordo ortográfico. 

O tópico que tinha antes era este :
https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/29

Actualização e Nocturno são antes do acordo ortográfico. 
Abraço
![Screenshot_2019-07-05-14-50-37-761_com android chrome](https://user-images.githubusercontent.com/37287217/60727018-d3ada880-9f34-11e9-96e6-9e47d41f7b9f.jpg)
![Screenshot_2019-07-05-14-51-02-837_com android chrome](https://user-images.githubusercontent.com/37287217/60727025-d6a89900-9f34-11e9-8208-3aa32c47aeb5.jpg)

**Comment by KcNirvana** [comment]
Boas rapaz...
Toda a tradução está como antes do acordo ortográfico e para não estar a alterar tudo vai manter-se assim.
Obrigado.
Abraç
