### ISSUE TITLE
Notificações 

### ISSUE THREAD

**Issue by Mainframe25** [KcNirvana/MIUI-XML-10-PORTUGUESE#8]
No mi4, não permite ver o contudo de notificações múltiplas no ecrã de bloqueio sem abrir as apps. 

Na versão anterior conseguia se isto carregando com 2 dedos na notificação pretendida e deslizando para baixo.

Obrigado

**Comment by KcNirvana** [comment]
Boas,
Tens de carregar na seta que está ao lado do nome da aplicação para ele expandir as notificações.
Obrigado.

Abraço

**Comment by Mainframe25** [comment]
Boa tarde,




No Mi4 não aparece a seta que menciona.

Obrigado, Em 07/08/2018 10:04, KcNirvana <notifications@github.com> escreveu:Boas,
Tens de carregar na seta que está ao lado do nome da aplicação para ele expandir as notificações.
Obrigado.
Abraço

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/KcNirvana/MIUI-XML-10-PORTUGUESE","title":"KcNirvana/MIUI-XML-10-PORTUGUESE","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KcNirvana in #8: Boas,\r\nTens de carregar na seta que está ao lado do nome da aplicação para ele expandir as notificações.\r\nObrigado.\r\n\r\nAbraço"}],"action":{"name":"View Issue","url":"https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/8#issuecomment-410987508"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/8#issuecomment-410987508",
"url": "https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/8#issuecomment-410987508",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [KcNirvana/MIUI-XML-10-PORTUGUESE] Notificações  (#8)",
"sections": [
{
"text": "",
"activityTitle": "**KcNirvana**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@KcNirvana",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"KcNirvana/MIUI-XML-10-PORTUGUESE\",\n\"issueId\": 8,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/issues/8#issuecomment-410987508"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 365251013\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by KcNirvana** [comment]
Boas...
Podes mandar 1 printscreen sff?

**Comment by KcNirvana** [comment]
@Franciscoestima
Boas...
Tás no issue errado.

Abraço
