### ISSUE TITLE
Relógio vertical 

### ISSUE THREAD

**Issue by Franciscoestima** [KcNirvana/MIUI-XML-10-PORTUGUESE#9]
![screenshot_2018-08-08-09-13-03-863_com android settings](https://user-images.githubusercontent.com/25460498/43825945-f029fd66-9aed-11e8-8c0e-e03478d8e0c9.png)

**Comment by KcNirvana** [comment]
Bom dia,
Alteração já corrigida com https://github.com/KcNirvana/MIUI-XML-10-PORTUGUESE/commit/792c271a1edae3f99937280e08be737dbf33b074

Obrigado
